#ifndef INLINE4_WARP3DPPC_H
#define INLINE4_WARP3DPPC_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

/* Inline macros for Interface "main" */
/*#define PtInit(buf, bufsize, frequency, modtype) Iwarp3dppc->PtInit(buf, bufsize, frequency, modtype) */

#endif /* INLINE4_PTPLAY_H */
