#ifndef WARP3DPPC_INTERFACE_DEF_H
#define WARP3DPPC_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 51.8.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

struct warp3dppcIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct warp3dppcIFace *Self);
	ULONG APICALL (*Release)(struct warp3dppcIFace *Self);
	void APICALL (*Expunge)(struct warp3dppcIFace *Self);
	struct Interface * APICALL (*Clone)(struct warp3dppcIFace *Self);
};

#endif /* WARP3DPPC_INTERFACE_DEF_H */
