/*
** This file was automatically generated by fdtrans 51.19.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#define __USE_BASETYPE__
#define __USE_INLINE__
#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/warp3dppc.h>
#include <proto/warp3d.h>
#include <interfaces/warp3d.h>



static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }

APTR stub_CreateContext(ULONG * error, struct TagItem * CCTags)
{
	W3D_Context *context;
	context = W3D_CreateContext(error, CCTags);
	return (context);
}

/***************************************************************************************************/

void stub_DestroyContext(W3D_Context * context)
{
    W3D_DestroyContext(context);
    return;
}

/***************************************************************************************************/

ULONG stub_GetState (W3D_Context * context, ULONG state) 
{
	ULONG result;
	result = W3D_GetState(context, state);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetState(W3D_Context * context, ULONG state, ULONG action)
{
	ULONG result;
	result = W3D_SetState(context, state, action);
	return (result);
}

/***************************************************************************************************/

ULONG stub_CheckDriver(void)
{
	ULONG result;
	result = W3D_CheckDriver();
	return (result);
}

/***************************************************************************************************/

ULONG stub_LockHardware(W3D_Context * context)
{
	ULONG result;
	result = W3D_LockHardware(context);
	return (result);
}

/***************************************************************************************************/

void stub_UnLockHardware(W3D_Context * context)
{
	W3D_UnLockHardware(context);
	return;
}

/***************************************************************************************************/

void stub_WaitIdle(W3D_Context * context)
{
	W3D_WaitIdle(context);	
	return;
}

/***************************************************************************************************/

ULONG stub_CheckIdle(W3D_Context * context)
{
	ULONG result;
	result = W3D_CheckIdle(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_Query(W3D_Context * context, ULONG query, ULONG destfmt)
{
	ULONG result;
	result = W3D_Query(context, query, destfmt);
	return (result);
}

/***************************************************************************************************/

ULONG stub_GetTexFmtInfo(W3D_Context * context, ULONG format, ULONG destfmt)
{
	ULONG result;
	result = W3D_GetTexFmtInfo(context, format, destfmt);
	return (result);
}

/***************************************************************************************************/

APTR stub_AllocTexObj(W3D_Context * context, ULONG * error, struct TagItem * ATOTags)
{
	W3D_Texture *texture;
	texture = W3D_AllocTexObj(context, error, ATOTags);
	return (texture);
}

/***************************************************************************************************/

void stub_FreeTexObj(W3D_Context * context, W3D_Texture * texture)
{
	W3D_FreeTexObj(context, texture);
	return;
}

/***************************************************************************************************/

void stub_ReleaseTexture(W3D_Context * context, W3D_Texture * texture)
{
	W3D_ReleaseTexture(context, texture);
	return;
}

/***************************************************************************************************/

void stub_FlushTextures(W3D_Context * context)
{
	W3D_FlushTextures(context);
	return;
}

/***************************************************************************************************/

ULONG stub_SetFilter(W3D_Context * context, W3D_Texture * texture, ULONG min, ULONG mag)
{
	ULONG result;
	result = W3D_SetFilter(context, texture, min, mag);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetTexEnv(W3D_Context * context, W3D_Texture * texture, ULONG envparam, W3D_Color * envcolor)
{
	ULONG result;
	result = W3D_SetTexEnv(context, texture, envparam, envcolor);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetWrapMode(W3D_Context * context, W3D_Texture * texture, ULONG mode_s, ULONG mode_t, W3D_Color * bordercolor)
{
	ULONG result;
	result = W3D_SetWrapMode(context, texture, mode_s, mode_t, bordercolor);
	return (result);
}

/***************************************************************************************************/

ULONG stub_UpdateTexImage(W3D_Context * context, W3D_Texture * texture, void * teximage, int level, ULONG * palette)
{
	ULONG result;
	result = W3D_UpdateTexImage(context, texture, teximage, level, palette);
	return (result);
}

/***************************************************************************************************/

ULONG stub_UploadTexture(W3D_Context * context, W3D_Texture * texture)
{
	ULONG result;
	result = W3D_UploadTexture(context, texture);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawLine(W3D_Context * context, W3D_Line * line)
{
	ULONG result;
	result = W3D_DrawLine(context, line);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawPoint(W3D_Context * context, W3D_Point * point)
{
	ULONG result;
	result = W3D_DrawPoint(context, point);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawTriangle(W3D_Context * context, W3D_Triangle * triangle)
{
	ULONG result;
	result = W3D_DrawTriangle(context, triangle);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawTriFan(W3D_Context * context, W3D_Triangles * triangles)
{
	ULONG result;
	result = W3D_DrawTriFan(context, triangles);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawTriStrip(W3D_Context * context, W3D_Triangles * triangles)
{
	ULONG result;
	result = W3D_DrawTriStrip(context, triangles);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetAlphaMode(W3D_Context * context, ULONG mode, W3D_Float * refval)
{
	ULONG result;
	result = W3D_SetAlphaMode(context, mode, refval);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetBlendMode(W3D_Context * context, ULONG srcfunc, ULONG dstfunc)
{
	ULONG result;
	result = W3D_SetBlendMode(context, srcfunc, dstfunc);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetDrawRegion(W3D_Context * context, struct BitMap * bm, int yoffset, W3D_Scissor * scissor)
{
	ULONG result;
	result = W3D_SetDrawRegion(context, bm, yoffset, scissor);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetFogParams(W3D_Context * context, W3D_Fog * fogparams, ULONG fogmode)
{
	ULONG result;
	result = W3D_SetFogParams(context, fogparams, fogmode);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetColorMask(W3D_Context * context, W3D_Bool red, W3D_Bool green, W3D_Bool blue, W3D_Bool alpha)
{
	ULONG result;
	result = W3D_SetColorMask(context, red, green, blue, alpha);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetStencilFunc(W3D_Context * context, ULONG func, ULONG refvalue, ULONG mask)
{
	ULONG result;
	result = W3D_SetStencilFunc(context, func, refvalue, mask);
	return (result);
}

/***************************************************************************************************/

ULONG stub_AllocZBuffer(W3D_Context * context)
{
	ULONG result;
	result = W3D_AllocZBuffer(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_FreeZBuffer(W3D_Context * context)
{
	ULONG result;
	result = W3D_FreeZBuffer(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ClearZBuffer(W3D_Context * context, W3D_Double * clearvalue)
{
	ULONG result;
	result = W3D_ClearZBuffer(context, clearvalue);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ReadZPixel(W3D_Context * context, ULONG x, ULONG y, W3D_Double * z)
{
	ULONG result;
	result = W3D_ReadZPixel(context, x, y, z);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ReadZSpan(W3D_Context * context, ULONG x, ULONG y, ULONG n, W3D_Double * z)
{
	ULONG result;
	result = W3D_ReadZSpan(context, x, y, n, z);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetZCompareMode(W3D_Context * context, ULONG mode)
{
	ULONG result;
	result = W3D_SetZCompareMode(context, mode);
	return (result);
}

/***************************************************************************************************/

ULONG stub_AllocStencilBuffer(W3D_Context * context)
{
	ULONG result;
	result = W3D_AllocStencilBuffer(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ClearStencilBuffer(W3D_Context * context, ULONG * clearval)
{
	ULONG result;
	result = W3D_ClearStencilBuffer(context, clearval);
	return (result);
}

/***************************************************************************************************/

ULONG stub_FillStencilBuffer(W3D_Context * context, ULONG x, ULONG y, ULONG width, ULONG height, ULONG depth, void * data)
{
	ULONG result;
	result = W3D_FillStencilBuffer(context, x, y, width, height, depth, data);
	return (result);
}

/***************************************************************************************************/

ULONG stub_FreeStencilBuffer(W3D_Context * context)
{
	ULONG result;
	result = W3D_FreeStencilBuffer(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ReadStencilPixel(W3D_Context * context, ULONG x, ULONG y, ULONG * st)
{
	ULONG result;
	result = W3D_ReadStencilPixel(context, x, y, st);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ReadStencilSpan(W3D_Context * context, ULONG x, ULONG y, ULONG n, ULONG * st)
{
	ULONG result;
	result = W3D_ReadStencilSpan(context, x, y, n, st);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetLogicOp(W3D_Context * context, ULONG operation)
{
	ULONG result;
	result = W3D_SetLogicOp(context, operation);
	return (result);
}

/***************************************************************************************************/

ULONG stub_Hint(W3D_Context * context, ULONG mode, ULONG quality)
{
	ULONG result;
	result = W3D_Hint(context, mode, quality);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetDrawRegionWBM(W3D_Context * context, W3D_Bitmap * bitmap, W3D_Scissor * scissor)
{
	ULONG result;
	result = W3D_SetDrawRegionWBM(context, bitmap, scissor);
	return (result);
}

/***************************************************************************************************/

ULONG stub_GetDriverState(W3D_Context * context)
{
	ULONG result;
	result = W3D_GetDriverState(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_Flush(W3D_Context * context)
{
	ULONG result;
	result = W3D_Flush(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetPenMask(W3D_Context * context, ULONG pen)
{
	ULONG result;
	result = W3D_SetPenMask(context, pen);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetStencilOp(W3D_Context * context, ULONG sfail, ULONG dpfail, ULONG dppass)
{
	ULONG result;
	result = W3D_SetStencilOp(context, sfail, dpfail, dppass);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetWriteMask(W3D_Context * context, ULONG mask)
{
	ULONG result;
	result = W3D_SetWriteMask(context, mask);
	return (result);
}

/***************************************************************************************************/

ULONG stub_WriteStencilPixel(W3D_Context * context, ULONG x, ULONG y, ULONG st)
{
	ULONG result;
	result = W3D_WriteStencilPixel(context, x, y, st);
	return (result);
}

/***************************************************************************************************/

ULONG stub_WriteStencilSpan(W3D_Context * context, ULONG x, ULONG y, ULONG n, ULONG * st, UBYTE * mask)
{
	ULONG result;
	result = W3D_WriteStencilSpan(context, x, y, n, st, mask);
	return (result);
}

/***************************************************************************************************/

void stub_WriteZPixel(W3D_Context * context, ULONG x, ULONG y, W3D_Double * z)
{
	W3D_WriteZPixel(context, x, y, z);
	return;
}

/***************************************************************************************************/

void stub_WriteZSpan(W3D_Context * context, ULONG x, ULONG y, ULONG n, W3D_Double * z, UBYTE * mask)
{
	W3D_WriteZSpan(context, x, y, n, z, mask);
	return;
}

/***************************************************************************************************/

ULONG stub_SetCurrentColor(W3D_Context * context, W3D_Color * color)
{
	ULONG result;
	result = W3D_SetCurrentColor(context, color);
	return (result);
}

/***************************************************************************************************/

ULONG stub_SetCurrentPen(W3D_Context * context, ULONG pen)
{
	ULONG result;
	result = W3D_SetCurrentPen(context, pen);
	return (result);
}

/***************************************************************************************************/

ULONG stub_UpdateTexSubImage(W3D_Context * context, W3D_Texture * texture, void * teximage, ULONG lev, ULONG * palette, W3D_Scissor * scissor, ULONG srcbpr)
{
	ULONG result;
	result = W3D_UpdateTexSubImage(context, texture, teximage, lev, palette, scissor, srcbpr);
	return (result);
}

/***************************************************************************************************/

ULONG stub_FreeAllTexObj(W3D_Context * context)
{
	ULONG result;
	result = W3D_FreeAllTexObj(context);
	return (result);
}

/***************************************************************************************************/

ULONG stub_GetDestFmt(void)
{
	ULONG result;
	result = W3D_GetDestFmt();
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawLineStrip(W3D_Context * context, W3D_Lines * lines)
{
	ULONG result;
	result = W3D_DrawLineStrip(context, lines);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawLineLoop(W3D_Context * context, W3D_Lines * lines)
{
	ULONG result;
	result = W3D_DrawLineLoop(context, lines);
	return (result);
}

/***************************************************************************************************/

APTR stub_GetDrivers(void)
{
	W3D_Driver ** driver;
	driver = W3D_GetDrivers();
	return (driver);
}

/***************************************************************************************************/

ULONG stub_QueryDriver(W3D_Driver * driver, ULONG query, ULONG destfmt)
{
	ULONG result;
	result = W3D_QueryDriver(driver, query, destfmt);
	return (result);
}

/***************************************************************************************************/

ULONG stub_GetDriverTexFmtInfo(W3D_Driver * driver, ULONG format, ULONG destfmt)
{
	ULONG result;
	result = W3D_GetDriverTexFmtInfo(driver, format, destfmt);
	return (result);
}

/***************************************************************************************************/

ULONG stub_RequestMode(struct TagItem * taglist)
{
	ULONG result;
	result = W3D_RequestMode(taglist);
	return (result);
}

/***************************************************************************************************/

void stub_SetScissor(W3D_Context * context, W3D_Scissor * scissor)
{
	W3D_SetScissor(context, scissor);
	return;
}

/***************************************************************************************************/

void stub_FlushFrame(W3D_Context * context)
{
	W3D_FlushFrame(context);	
	return;
}

/***************************************************************************************************/

APTR stub_TestMode(ULONG ModeID)
{
	W3D_Driver * driver;
	driver = W3D_TestMode(ModeID);
	return (driver);
}

/***************************************************************************************************/

ULONG stub_SetChromaTestBounds(W3D_Context * context, W3D_Texture * texture, ULONG rgba_lower, ULONG rgba_upper, ULONG mode)
{
	ULONG result;
	result = W3D_SetChromaTestBounds(context, texture, rgba_lower, rgba_upper, mode);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ClearDrawRegion(W3D_Context * context, ULONG color)
{
	ULONG result;
	result = W3D_ClearDrawRegion(context, color);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawTriangleV(W3D_Context * context, W3D_TriangleV * triangle)
{
	ULONG result;
	result = W3D_DrawTriangleV(context, triangle);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawTriFanV(W3D_Context * context, W3D_TrianglesV * triangles)
{
	ULONG result;
	result = W3D_DrawTriFanV(context, triangles);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawTriStripV(W3D_Context * context, W3D_TrianglesV * triangles)
{
	ULONG result;
	result = W3D_DrawTriStripV(context, triangles);
	return (result);
}

/***************************************************************************************************/

APTR stub_GetScreenmodeList(void)
{
	W3D_ScreenMode * list;
	list = W3D_GetScreenmodeList();
	return (list);
}

/***************************************************************************************************/

void stub_FreeScreenmodeList(W3D_ScreenMode * list)
{
	W3D_FreeScreenmodeList(list);
	return;
}

/***************************************************************************************************/

ULONG stub_BestModeID(struct TagItem * tags)
{
	ULONG result;
	result = W3D_BestModeID(tags);
	return (result);
}

/***************************************************************************************************/

ULONG stub_VertexPointer(W3D_Context * context, void * pointer, int stride, ULONG mode, ULONG flags)
{
	ULONG result;
	result = W3D_VertexPointer(context, pointer, stride, mode, flags);
	return (result);
}

/***************************************************************************************************/

ULONG stub_TexCoordPointer(W3D_Context * context, void * pointer, int stride, int unit, int off_v, int off_w, ULONG flags)
{
	ULONG result;
	result = W3D_TexCoordPointer(context, pointer, stride, unit, off_v, off_w, flags);
	return (result);
}

/***************************************************************************************************/

ULONG stub_ColorPointer(W3D_Context * context, void * pointer, int stride, ULONG format, ULONG mode, ULONG flags)
{
	ULONG result;
	result = W3D_ColorPointer(context, pointer, stride, format, mode, flags);
	return (result);
}

/***************************************************************************************************/

ULONG stub_BindTexture(W3D_Context * context, ULONG tmu, W3D_Texture * texture)
{
	ULONG result;
	result = W3D_BindTexture(context, tmu, texture);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawArray(W3D_Context * context, ULONG primitive, ULONG base, ULONG count)
{
	ULONG result;
	result = W3D_DrawArray(context, primitive, base, count);
	return (result);
}

/***************************************************************************************************/

ULONG stub_DrawElements(W3D_Context * context, ULONG primitive, ULONG type, ULONG count, void * indices)
{
	ULONG result;
	result = W3D_DrawElements(context, primitive, type, count, indices);
	return (result);
}

/***************************************************************************************************/

void stub_SetFrontFace(W3D_Context * context, ULONG direction)
{
	W3D_SetFrontFace(context, direction);
	return;
}

/***************************************************************************************************/

CONST APTR VecTable68K[] =
{
	NULL,						/*open*/
	NULL,						/*close*/
	NULL,
	NULL,
	(APTR)stub_CreateContext,
	(APTR)stub_DestroyContext,
	(APTR)stub_GetState,
	(APTR)stub_SetState,
	(APTR)stub_CheckDriver,
	(APTR)stub_LockHardware,
	(APTR)stub_UnLockHardware,
	(APTR)stub_WaitIdle,
	(APTR)stub_CheckIdle,
	(APTR)stub_Query,
	(APTR)stub_GetTexFmtInfo,
	(APTR)stub_AllocTexObj,
	(APTR)stub_FreeTexObj,
	(APTR)stub_ReleaseTexture,
	(APTR)stub_FlushTextures,
	(APTR)stub_SetFilter,
	(APTR)stub_SetTexEnv,
	(APTR)stub_SetWrapMode,
	(APTR)stub_UpdateTexImage,
	(APTR)stub_UploadTexture,
	(APTR)stub_DrawLine,
	(APTR)stub_DrawPoint,
	(APTR)stub_DrawTriangle,
	(APTR)stub_DrawTriFan,
	(APTR)stub_DrawTriStrip,
	(APTR)stub_SetAlphaMode,
	(APTR)stub_SetBlendMode,
	(APTR)stub_SetDrawRegion,
	(APTR)stub_SetFogParams,
	(APTR)stub_SetColorMask,
	(APTR)stub_SetStencilFunc,
	(APTR)stub_AllocZBuffer,
	(APTR)stub_FreeZBuffer,
	(APTR)stub_ClearZBuffer,
	(APTR)stub_ReadZPixel,
	(APTR)stub_ReadZSpan,
	(APTR)stub_SetZCompareMode,
	(APTR)stub_AllocStencilBuffer,
	(APTR)stub_ClearStencilBuffer,
	(APTR)stub_FillStencilBuffer,
	(APTR)stub_FreeStencilBuffer,
	(APTR)stub_ReadStencilPixel,
	(APTR)stub_ReadStencilSpan,
	(APTR)stub_SetLogicOp,
	(APTR)stub_Hint,
	(APTR)stub_SetDrawRegionWBM,
	(APTR)stub_GetDriverState,
	(APTR)stub_Flush,
	(APTR)stub_SetPenMask,
	(APTR)stub_SetStencilOp,
	(APTR)stub_SetWriteMask,
	(APTR)stub_WriteStencilPixel,
	(APTR)stub_WriteStencilSpan,
	(APTR)stub_WriteZPixel,
	(APTR)stub_WriteZSpan,
	(APTR)stub_SetCurrentColor,
	(APTR)stub_SetCurrentPen,
	(APTR)stub_UpdateTexSubImage,
	(APTR)stub_FreeAllTexObj,
	(APTR)stub_GetDestFmt,
	(APTR)stub_DrawLineStrip,
	(APTR)stub_DrawLineLoop,
	(APTR)stub_GetDrivers,
	(APTR)stub_QueryDriver,
	(APTR)stub_GetDriverTexFmtInfo,
	(APTR)stub_RequestMode,
	(APTR)stub_SetScissor,
	(APTR)stub_FlushFrame,
	(APTR)stub_TestMode,
	(APTR)stub_SetChromaTestBounds,
	(APTR)stub_ClearDrawRegion,
	(APTR)stub_DrawTriangleV,
	(APTR)stub_DrawTriFanV,
	(APTR)stub_DrawTriStripV,
	(APTR)stub_GetScreenmodeList,
	(APTR)stub_FreeScreenmodeList,
	(APTR)stub_BestModeID,
	(APTR)stub_VertexPointer,
	(APTR)stub_TexCoordPointer,
	(APTR)stub_ColorPointer,
	(APTR)stub_BindTexture,
	(APTR)stub_DrawArray,
	(APTR)stub_DrawElements,
	(APTR)stub_SetFrontFace,
	(CONST_APTR)-1
};
