#ifndef _WARP3DPPC_PATCH_H_
#define	_WARP3DPPC_PATCH_H_

#define PATCH_DRAWELEMENTS      0x1
#define PATCH_DRAWARRAY         0x2
#define PATCH_DRAWLINE          0x4
#define PATCH_ALL               PATCH_DRAWELEMENTS|PATCH_DRAWARRAY|PATCH_DRAWLINE

#endif	/* _WARP3DPPC_PATCH_H_ */

